// https://edabit.com/challenge/mTT8M47D6EuEdTXLv

function fullKeyName(piece) {
	const arr = piece.split(' ')
        , inIndex = arr.indexOf('in')
        , majorCharCode = arr[inIndex + 1].charCodeAt(0)
        , key = majorCharCode > 64 && majorCharCode < 91
			? arr[inIndex + 1] + " major"
			: arr[inIndex + 1].substring(0, 1).toUpperCase() 
				+ arr[inIndex + 1].substring(1) + " minor";

	return arr.slice(0, inIndex + 1).join(' ') + " " + key;
}

const Test = require('../../test.js');
Test.assertEquals(fullKeyName("Prelude in C"), "Prelude in C major")
Test.assertEquals(fullKeyName("Fugue in c"), "Fugue in C minor")
Test.assertEquals(fullKeyName("Toccata and Fugue in d"), "Toccata and Fugue in D minor")
Test.assertEquals(fullKeyName("a Fugue in c"), "a Fugue in C minor")
Test.assertEquals(fullKeyName("Sonata in D"), "Sonata in D major")
Test.assertEquals(fullKeyName("Opera in eb"), "Opera in Eb minor")
Test.assertEquals(fullKeyName("Toccata in ab"), "Toccata in Ab minor")
Test.assertEquals(fullKeyName("Toccata in f"), "Toccata in F minor")
Test.assertEquals(fullKeyName("Symphony in C#"), "Symphony in C# major")
Test.assertEquals(fullKeyName("Mass in c"), "Mass in C minor")
Test.assertEquals(fullKeyName("Toccata in c"), "Toccata in C minor")
Test.assertEquals(fullKeyName("Prelude in Ab"), "Prelude in Ab major")
Test.assertEquals(fullKeyName("Concerto in f#"), "Concerto in F# minor")
Test.assertEquals(fullKeyName("Symphony in eb"), "Symphony in Eb minor")
Test.assertEquals(fullKeyName("Sonata in a"), "Sonata in A minor")
Test.assertEquals(fullKeyName("Sonata in e"), "Sonata in E minor")
Test.assertEquals(fullKeyName("Concerto in c#"), "Concerto in C# minor")
Test.assertEquals(fullKeyName("Opera in f"), "Opera in F minor")
Test.assertEquals(fullKeyName("Mass in c"), "Mass in C minor")
Test.assertEquals(fullKeyName("Symphony in D"), "Symphony in D major")
Test.assertEquals(fullKeyName("Fugue in d"), "Fugue in D minor")
Test.assertEquals(fullKeyName("Fugue in eb"), "Fugue in Eb minor")
Test.assertEquals(fullKeyName("Fugue in F"), "Fugue in F major")
Test.assertEquals(fullKeyName("Mass in c#"), "Mass in C# minor")
Test.assertEquals(fullKeyName("Requiem in C"), "Requiem in C major")
Test.assertEquals(fullKeyName("Prelude in Eb"), "Prelude in Eb major")
Test.assertEquals(fullKeyName("Prelude in Bb"), "Prelude in Bb major")
Test.assertEquals(fullKeyName("Fugue in g"), "Fugue in G minor")
Test.assertEquals(fullKeyName("Requiem in c#"), "Requiem in C# minor")
Test.assertEquals(fullKeyName("Opera in f"), "Opera in F minor")
Test.assertEquals(fullKeyName("Prelude in G"), "Prelude in G major")
Test.assertEquals(fullKeyName("Symphony in Eb"), "Symphony in Eb major")
Test.assertEquals(fullKeyName("Symphony in eb"), "Symphony in Eb minor")
Test.assertEquals(fullKeyName("Sonata in e"), "Sonata in E minor")
Test.assertEquals(fullKeyName("Fugue in g"), "Fugue in G minor")
Test.assertEquals(fullKeyName("Sonata in A"), "Sonata in A major")
Test.assertEquals(fullKeyName("Requiem in b"), "Requiem in B minor")
Test.assertEquals(fullKeyName("Sonata in eb"), "Sonata in Eb minor")
Test.assertEquals(fullKeyName("Prelude in c#"), "Prelude in C# minor")
Test.assertEquals(fullKeyName("Fugue in F"), "Fugue in F major")
Test.assertEquals(fullKeyName("Concerto in ab"), "Concerto in Ab minor")
Test.assertEquals(fullKeyName("Toccata in F#"), "Toccata in F# major")
Test.assertEquals(fullKeyName("Symphony in Bb"), "Symphony in Bb major")
Test.assertEquals(fullKeyName("Waltz in f#"), "Waltz in F# minor")
Test.assertEquals(fullKeyName("Prelude in Eb"), "Prelude in Eb major")
Test.assertEquals(fullKeyName("Requiem in b"), "Requiem in B minor")
Test.assertEquals(fullKeyName("Concerto in Bb"), "Concerto in Bb major")
Test.assertEquals(fullKeyName("Fugue in G"), "Fugue in G major")
Test.assertEquals(fullKeyName("Mass in eb"), "Mass in Eb minor")
Test.assertEquals(fullKeyName("Symphony in Ab"), "Symphony in Ab major")
Test.assertEquals(fullKeyName("Symphony in f"), "Symphony in F minor")
Test.assertEquals(fullKeyName("Fugue in f#"), "Fugue in F# minor")
Test.assertEquals(fullKeyName("Prelude in D"), "Prelude in D major")
Test.assertEquals(fullKeyName("Concerto in bb"), "Concerto in Bb minor")